export enum HISTORY_TYPE {
  DEPOSIT = "DEPOSIT",
  WITHDRAW = "WITHDRAW",
  WEEKLY_COUPON = "WEEKLY_COUPON",
  OPTION_PAYOUT = "OPTION_PAYOUT"
}

export enum WITHDRAW_TYPE {
  NONE = "NONE",
  PRINCIPAL = "PRINCIPAL",
  COUPON = "COUPON",
  OPTION = "OPTION",
}

export enum SUPPORT_CHAIN_IDS {
  GOERLI = 5,
  MOONBEAM_ALPHA = 1287,
  ARBITRUM_GOERLI = 421613
}
